let products = [
    { id: "1", name: "Porta Canetas", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 20, image: "", amount: 10 },
    { id: "2", name: "Chaveiro Nossa Senhora", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 18.00, image: "", amount: 60 },
    { id: "3", name: "Réplica Carro de Boi", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 17.50, image: "", amount: 40 },
    { id: "4", name: "Caminhao de gado", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 2500.00, image: "", amount: 5 },
    { id: "5", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "6", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "7", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "8", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "9", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "10", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "11", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "12", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "13", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "14", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
    { id: "15", name: "Adesivo de Time", description: "Esta é a descricao do produto fake, ela deve conter mais de uma linha ", price: 500.00, image: "", amount: 10 },
];
